# Form implementation generated from reading ui file '.\windows\ui\vizualizar_window.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_vizualizar_window(object):

    def setupUi(self, vizualizar_window):
        vizualizar_window.setObjectName("vizualizar_window")
        vizualizar_window.resize(248, 237)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        vizualizar_window.setFont(font)
        vizualizar_window.setStyleSheet("background-color: rgb(44, 44, 44);\n"
"color: rgb(255, 105, 182);")
        self.centralwidget = QtWidgets.QWidget(vizualizar_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, -20, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 30, 231, 181))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        vizualizar_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(vizualizar_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 248, 22))
        self.menubar.setObjectName("menubar")
        self.menuMENU = QtWidgets.QMenu(self.menubar)
        self.menuMENU.setObjectName("menuMENU")
        vizualizar_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(vizualizar_window)
        self.statusbar.setObjectName("statusbar")
        vizualizar_window.setStatusBar(self.statusbar)
        self.actionVisualizar_Senhas = QtGui.QAction(vizualizar_window)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionVisualizar_Senhas.setFont(font)
        self.actionVisualizar_Senhas.setObjectName("actionVisualizar_Senhas")
        self.actionGerar_senhas = QtGui.QAction(vizualizar_window)
        self.actionGerar_senhas.setObjectName("actionGerar_senhas")
        self.actionAdicionar_senhas = QtGui.QAction(vizualizar_window)
        self.actionAdicionar_senhas.setObjectName("actionAdicionar_senhas")
        self.menuMENU.addAction(self.actionVisualizar_Senhas)
        self.menuMENU.addAction(self.actionGerar_senhas)
        self.menuMENU.addAction(self.actionAdicionar_senhas)
        self.menubar.addAction(self.menuMENU.menuAction())

        self.retranslateUi(vizualizar_window)
        QtCore.QMetaObject.connectSlotsByName(vizualizar_window)

    def retranslateUi(self, vizualizar_window):
        _translate = QtCore.QCoreApplication.translate
        vizualizar_window.setWindowTitle(_translate("vizualizar_window", "MainWindow"))
        self.label.setText(_translate("vizualizar_window", "Password Manager"))
        self.menuMENU.setTitle(_translate("vizualizar_window", "MENU"))
        self.actionVisualizar_Senhas.setText(_translate("vizualizar_window", "Visualizar senhas"))
        self.actionGerar_senhas.setText(_translate("vizualizar_window", "Gerador de senhas"))
        self.actionAdicionar_senhas.setText(_translate("vizualizar_window", "Adicionar senhas"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    vizualizar_window = QtWidgets.QMainWindow()
    ui = Ui_vizualizar_window()
    ui.setupUi(vizualizar_window)
    vizualizar_window.show()
    sys.exit(app.exec())
